apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-jmeter
spec:
  params:
    - name: TEST_DIR
      type: string
      description: "Directory containing test files"
      default: "TestPlans"
  workspaces:
    - name: data-workspace
      description: "Workspace for test data"
      mountPath: /data
  steps:
    - name: run-shell
      image: quay.io/springdo/jmeter:5.6.3
      script: |
        #!/usr/bin/env sh
        set -xe
        
        # ls /data/$(params.TEST_DIR)
        ls /data/

        sleep 360