apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-deploy
spec:
  params:
    - default: .
      description: The context directory within the source
      name: CONTEXT_DIR
      type: string
    - description: for example --set appName=blah
      name: VALUES_OVERRIDES
      type: string
    - default: abc
      description: 'Suffix to add to the agent deployments, defaults to abc'
      name: APP_NAME
      type: string
  steps:
    - image: 'quay.io/redhat-cop/tool-box:latest'
      name: bash-command
      script: |
        set -xe
        ls $(workspaces.source.path)
 
        echo "Installing / upgrading the grid"
        helm upgrade --install $(params.APP_NAME) --set appName=$(params.APP_NAME) $(params.VALUES_OVERRIDES) chart
      securityContext:
        runAsUser: 0
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
    - image: 'quay.io/openshift/origin-cli:4.12'
      name: verify
      script: |
        #!/bin/sh
        echo "verify the deployment by checking the deployments have happended..."
        echo "NOTE - lazy mode only checking one deployement [deployment/jmeter-agent-0-$(params.APP_NAME)]"
        oc rollout status --timeout=2m deployment/jmeter-agent-0-$(params.APP_NAME)
  workspaces:
    - name: source