apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-jmeter
spec:
  params:
    - default: TestPlans
      description: Directory containing test files
      name: TEST_DIR
      type: string
    - default: '3'
      description: number of static agents to use (3)
      name: JMETER_AGENTS
      type: string
    - default: abc
      description: 'Suffix to add to the agent deployments, defaults to abc'
      name: APP_NAME
      type: string
  steps:
    - computeResources: {}
      image: 'quay.io/springdo/jmeter:5.6.3'
      name: run-jmeter
      script: |
        #!/bin/bash
        set -xe

        echo "\n\n  \U0001F9F9 Cleaning up left over bits \U0001F9F9"
        export T_DIR=/data/
        export R_DIR=${T_DIR}/report

        rm -rf ${T_DIR}/HelloWorld.jtl
        rm -rf ${R_DIR}
        rm -rf ${T_DIR}/jmeter.log
        mkdir -p ${R_DIR}

        ls $(workspaces.source.path)
        echo "Copy test files to thh mount"
        cp -vr $(workspaces.source.path)/$(params.TEST_DIR) /data/

        echo "\n\n \U0001F3C3‍♀️ Running the Jmeter shizzles \U0001F9EA"        
        export AGENT_LIST=""
        let x=0; while  [ $x -le $(params.JMETER_AGENTS) ]; do AGENT_LIST+="jmeter-agent-$x-$(params.APP_NAME),"; let x++; done
        echo "Agent List :: ${AGENT_LIST}" 
        jmeter -Dlog_level.jmeter=DEBUG -n -t ${T_DIR}/$(params.TEST_DIR)/*.jmx -l ${T_DIR}/HelloWorld.jtl -j ${T_DIR}/jmeter.log -Dserver.rmi.localport=1099 -Dserver_port=1099 -Jserver.rmi.ssl.disable=true -Jjmeter.reportgenerator.temp_dir=/tmp -R ${AGENT_LIST} -e -o ${R_DIR}

        echo "\n\n ==== jmeter.log ===="
        cat ${T_DIR}/jmeter.log

        echo "\n\n ==== Raw Test Report ===="
        cat ${T_DIR}/*.jtl

        echo "\n\n ==== HTML Test Report ===="
        echo "See HTML test report in ${R_DIR}/index.html"
        ls ${R_DIR}
      volumeMounts:
        - mountPath: /data
          name: test-data
      workingDir: $(workspaces.source.path)
  volumes:
    - name: test-data
      persistentVolumeClaim:
        claimName: jmeter-pvc-$(params.APP_NAME)
  workspaces:
    - description: Workspace from git clone
      name: source