{{- if .Values.agent.enabled }}
{{ $values := .Values }}
{{- range $i, $replica := until ( int .Values.agent.replicas ) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-agent-{{ $i }}-{{ $values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-agent-{{ $i }}-{{ $values.appName }}
  template:
    metadata:
      labels:
        app: jmeter-agent-{{ $i }}-{{ $values.appName }}
    spec:
      containers:
      - name: jmeter-agent-{{ $values.appName }}
        image: {{  $values.agent.image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: JVM_ARGS
          value: "-Xms{{ $values.agent.minMemoryLimit }} -Xmx{{ $values.agent.maxMemoryLimit }}"
        - name: MODE
          value: "SLAVE"
        command: ["/bin/bash", "-c"]
        args: ["cd /tmp && sh -c 'tail -F /tmp/jmeter-server.log >> /dev/stdout &' ; jmeter-server -Dserver.rmi.localport=50000 -Dserver_port=1099 -Jserver.rmi.ssl.disable=true"]
        ports:
        - containerPort: 1099
        - containerPort: 50000
        - containerPort: 4445
        resources:
          requests:
            cpu: {{ $values.agent.resources.requests.cpu }}
            memory: {{ $values.agent.resources.requests.memory }}
          limits:
            cpu: {{ $values.agent.resources.limits.cpu }}
            memory: {{ $values.agent.resources.limits.memory }}
        livenessProbe:
          exec:
            command:
            - cat
            - /opt/jmeter/apache-jmeter/bin/jmeter
        volumeMounts:
            - mountPath: /data
              name: jmeter-data-dir
      volumes:
        - name: jmeter-data-dir
          persistentVolumeClaim:
            claimName: jmeter-pvc-{{ $values.appName }}
{{- end }}
{{- end }}