---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jmeter-pvc-{{ .Values.appName }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName:  {{ .Values.pvc.storageClassName }}