---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jmeter-pvc-{{ .Values.appName }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: trident