kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jmeter-runs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: thin-csi
  volumeMode: Filesystem